### PR TITLE
Use rev/min instead of r/min for initial engine speed

### LINKED ISSUE #90: Units error (or incompatibiity?) in VehicleInterfaces\Engines\MinimalEngine.mo: r/min vs 1/min
I'm a new user of Modelica and the VehicleInterfaces package.

I'm using OpenModelica v1.18.0 (64bit) and VehicleInterfaces v2.0.0 on Windows 10.

When trying to simulate the VehicleInterfaces\Examples\SeriesHybrid.mo model, there is an error related to the "r/min" displayUnit (line 10).

I edited the file manually and changed this to "1/min" and it now works for me.

I've no idea whether this is a typo or whether it's a version incompatibility, but hopefully it'll help someone else even if the latter.

### PR DESCRIPTION
**Pull request by tobolar**
close #90

### CODE REVIEW

**Comment by tobolar** [comment]
@dietmarw The CI stucks since Friday. Probably we have here not the current CI as used for MSL. Can you help?

**Comment by sjoelund** [comment]
Push force or add a dummy commit probably helps. Sometimes the server on the other side messes up a request and sometimes github fails to deliver it.

**Comment by tobolar** [comment]
I have proceeded just according to you suggest. Let's see if it helps.

**Comment by tobolar** [comment]
No progress 8 hours later... :-(

**Comment by dietmarw** [comment]
Yes, travis has become highly unrelieable. That's why we switched MSL to GitHub actions.

**Comment by beutlich** [comment]
Well, nothing unexpected actually when I check https://travis-ci.org/github/modelica/VehicleInterfaces/requests. Last successful build on Travis CI Org was on 2020-09-07. Meanwhile Travis CI ported from Org to Com.

I can only recommend to take the CI using GitHub Actions from MSL as template and apply to VehicleInterfaces. We already did so for a few other repoitories and it worked like a charm.

**Comment by tobolar** [comment]
> I can only recommend to take the CI using GitHub Actions from MSL as template and apply to VehicleInterfaces.

Can I do it on my own? Probably not because Travis would block my PR on CI changes. ;-)

**Comment by sjoelund** [comment]
> Can I do it on my own? Probably not because Travis would block my PR on CI changes. ;-)

I disabled the Travis CI since it doesn't work. When the github actions are working, I can enforce it passing before merges.

**Comment by tobolar** [comment]
CI integrated in #94

**Pull request merged**
