### PR TITLE
Enable user-friendly dialog for replaceable road function

### LINKED ISSUE #89: Layout of road functions in Roads.Interfaces.Base
The **VehicleInterfaces.Roads.Interfaces.Base** is used as the base for many roads.  These roads add in many other parameters and replaceable functions so it would be good to group the road functions in **Base** into a Tab to tidy up the layout of these functions.  The description strings could also be improved and I think adding choicesAllMatching makes modifying these replaceable functions easier.

So I would like to propose that the road functions in **Base** be replaced with the following code.

```
  replaceable function position = VehicleInterfaces.Roads.Interfaces.positionBase
    "Function to get position at a road position" annotation (
    choicesAllMatching=true,
    Dialog(tab="Functions"),
    Documentation(info="<html>
<p>
The road position function returns the world location of the road location (s,w).
</p>
</html>"));
  replaceable function trackOffset = VehicleInterfaces.Roads.Interfaces.trackOffsetBase
    "Function to get position at a driving line position" annotation (
    choicesAllMatching=true,
    Dialog(tab="Functions"),
    Documentation(info="<html>
<p>
The track offset function returns the location of the driving line location (s,w).  This location can either be relative to the road centre line or in world coordinates.
</p>
</html>"));

  replaceable function normal = VehicleInterfaces.Roads.Interfaces.normalBase
    "Function to get road normal at a road position" annotation (
    choicesAllMatching=true,
    Dialog(tab="Functions"),
    Documentation(info="<html>
<p>
The normal function returns the normal of the road surface at (s,w).
</p>
</html>"));

  replaceable function headingDirection = VehicleInterfaces.Roads.Interfaces.headingDirectionBase
    "Function to get heading direction at a road position" annotation (
    choicesAllMatching=true,
    Dialog(tab="Functions"),
    Documentation(info="<html>
<p>
The heading direction function returns the direction in which the road is going at (s,w).
</p>
</html>"));

  replaceable function frictionCoefficient = VehicleInterfaces.Roads.Interfaces.frictionCoefficientBase
    "Function to get friction coefficient at road position" annotation (
    choicesAllMatching=true,
    Dialog(tab="Functions"),
    Documentation(info="<html>
<p>
The frictionCoefficient function returns the friction coefficient of the road at (s,w).
</p>
</html>"));
```

### PR DESCRIPTION
**Pull request by tobolar**
Close #89 

@GarronFish Can you review this PR?

### CODE REVIEW

**Comment by GarronFish** [comment]
Yes will do.

**Review by GarronFish — APPROVED** [review]
Checked the code changes and description strings and documentation.
Checked with Advanced.PedanticModelica=true; in Dymola
Ran multiple simulations with these code changes.
Everything worked as expected.

**Comment by tobolar** [comment]
Some comments to your suggestion in #89:

1. Regarding class documentation, esp. in the function trackOffset.
It is of course welcome to add more documentation to clarify the intension of the class. In this case ("... driving line location relative to the road centre line", etc.), I nontheless reduced the documentation and would prefer to add this in the base functions directly, e.g. in `VehicleInterfaces.Roads.Interfaces.trackOffsetBase`, etc. Optionally, the tutorial section of the Road could be a good place.

2. And, I call the corresponding tab "Road functions". I'm not so happy with it beut have no better idea.

**Comment by GarronFish** [comment]
Yes I agree with point 1. 

"Road functions" seems fine may be "Functions" is slightly better.

**Pull request merged**
