### PR TITLE
Updated for MSL 3.2.2 and changed icons

### PR DESCRIPTION
**Pull request by tobolar**
* Icon VariantLibrary marked as obsolete - using Modelica.Icons.VariantsPackage instead;
* Simplified Icons.Driveline: a lot of polygons replaced with rotated rectangles;
* Icons.SignalSubBusWithExplicitSignals: smoothed polygon in Diagram.

### CODE REVIEW

**Comment by dietmarw** [comment]
I like to wait with the merge until there is actually a MSL 3.2.2 released. It does not make sense to make that change right now.

**Comment by dietmarw** [comment]
Is there some **technical** requirement of MSL 3.2.2? I.e., does it use now any classes that don't exist in MSL 3.2.1 yet?

**Comment by tobolar** [comment]
There is actually no need to upgrade to MSL 3.2.2. In this pull request, there are just minor changes as have been in a couple of last requests. 
... and you are right to change the year in versiondate as well.

**Comment by dietmarw** [comment]
So could you update the PR?
PS: It's really unfortunate that we still don't have the possibility to specify multiple versions of a library in `uses` :frowning:

**Comment by tobolar** [comment]
The Copyright is defined on just one single place now, cf. issue #15. The icon is used as suggested in that issue.

**Comment by tobolar** [comment]
You mean to remove copyright? I can imagine there could be issues with the original developers and contributors.

**Comment by dietmarw** [comment]
One thing I noticed is that your PR pushes for a new release. Could you also update the README I can then cut/tag the release.

**Comment by tobolar** [comment]
I've tried to update README as well.

**Comment by dietmarw** [comment]
Thanks. I think all should be fine. I'll still hold off the merge until status of new MSL release is finally resolved. But I can adapt the uses annotation depending on the outcome. As you said, there is no conversion necessary anyway.

**Comment by tobolar** [comment]
Very well, thank's.

**Comment by dietmarw** [comment]
MSL 3.2.2 released now.

**Pull request merged**
