### PR TITLE
Removed duplicated variable "currentGear" from Interface.TransmissionControlBus

### PR DESCRIPTION
**Pull request by dariomangoni**
The variable `currentGear` is declared both in:
- _Transmission.Interface.StandardControlBus_
- _Interface.TransmissionControlBus_

resulting in a variable duplication.

The variable is deleted from _Interface.TransmissionControlBus_, since variables, as far as I can see, are usually declared in the component-specific derived classes.

### CODE REVIEW

**Comment by harmanpa** [comment]
It is true that currentGear is declared twice, however this commit removes it from the wrong declaration. If you delete currentGear from VehicleInterfaces.Transmission.Interfaces.StandardControlBus it will have no effect, deleting it from VehicleInterfaces.Interfaces.TransmissionControlBus however will affect classes that depend on this and not StandardControlBus.

**Comment by dariomangoni** [comment]
I'm a bit confused.

> If you delete currentGear from VehicleInterfaces.Transmission.Interfaces.StandardControlBus it will have no effect

that's right! In fact I deleted it from VehicleInterfaces.Interfaces.TransmissionControlBus!!!
-----
I'm supposing that "currentGear" is something that you want to have at the most derived level, i.e. in Transmission.Interface.StandardControlBus, right?

StandardControlBus is derived from VehicleInterfaces.Interface.TransmissionControlBus, thus it inherits its variables, including the misplaced "currentGear".

Deleting it from the base class (i.e. VehicleInterfaces.Interface.TransmissionControlBus) **as I actually did**, it will be reflected also in the derived class, in which instead you want to have "currentGear" declared.
That's what we want, isn't it?

**Comment by harmanpa** [comment]
StandardControlBus inherits currentGear from TransmissionControlBus, yes. But other classes (which we have to assume exist in other libraries) that extend from TransmissionControlBus also inherit it, hence we can't remove it from TransmissionControlBus for backwards-compatibility reasons.

We can however remove the declaration from StandardControlBus because this is a duplicate. When I say it will have no effect, that is a good thing, I mean it has no potential negative impacts.

**Comment by dariomangoni** [comment]
Oh, ok! Now I got it.
I let you fix the error, then. Personally I'm not sure if I would carry on with an error in the code just for backward compatibility, but that's your choice!

(and sorry for the big characters in the previous post, they came out with no intention! I probably pushed some wrong keys)

**Comment by harmanpa** [comment]
Thanks Dario, I will apply the fix and will check the other connectors for similar duplications. Thanks for pointing it out and please continue to contribute!

**Pull request closed without merging**
