### PR TITLE
Add license files

### PR DESCRIPTION
**Pull request by tbeu**
This PR adds the license file of the own work to

* the repository root for more transparency.
* the Reosurces/Licenses directory in preparation of MCP-0029 to better support tool vendors when distributing (derived work of) the VehicleInterfaces.

The license text was copied from [ModelicaLicense 1.1](https://modelica.org/licenses/ModelicaLicense1.1/ModelicaLicense1.1.txt/view.html).

See also https://github.com/modelica-3rdparty/Modelica_DeviceDrivers/pull/313

### CODE REVIEW

**Review by tobolar — COMMENTED** [review]
Nice. I'm only concerned about the same license text being placed in three different sources. Ok, mostly just the copyright's year will change but even then this is error prone.
IMO LICENSE.txt is the actual license file, all the others shall point to it.

**Comment by tbeu** [comment]
> Nice. I'm only concerned about the same license text being placed in three different sources. Ok, mostly just the copyright's year will change but even then this is error prone.

Every file served different purposes, though:
1. LICENSE.txt is for the GitHub repository to have it transparent on root and front page.
2. VehicleInterfaces.UsersGuide.License is for the online documentation
3. Resources/Licenses is for the tools to pack the necessary licence information when creating derived work (imagine FMUs).

> IMO LICENSE.txt is the actual license file, all the others shall point to it.

Having symbolic links for files in Git repositories does not work across different operating systems. Thus, we'd live with copied files.

**Comment by tobolar** [comment]
Ok. This shall be documented in a release process description, if there is any. (Wiki?)

**Comment by tbeu** [comment]
[Wiki](https://github.com/modelica/VehicleInterfaces/wiki) is now activated, though still empty.

**Comment by sjoelund** [comment]
> Having symbolic links for files in Git repositories does not work across different operating systems. Thus, we'd live with copied files.

Also, that top file might not be there when packaged up into a tool's distribution.

**Comment by tobolar** [comment]
First draft of a release process: https://github.com/modelica/VehicleInterfaces/wiki/Generating-a-new-VI-release

**Comment by dietmarw** [comment]
`versionBuild` shall no longer be used. Semver has a better much more reliable system and hence since MSL 4.0.0 versionBuild is also neither used nor mentioned any more.

**Pull request merged**
